import * as fs from 'fs';

class FileHandler {
  private filePath: string;

  constructor(filePath: string) {
    this.filePath = filePath;
  }

  // Write data to file (overwrites if file exists)
  writeFile(data: string): void {
    fs.writeFileSync(this.filePath, data, 'utf8');
    console.log(`File written successfully: ${this.filePath}`);
  }

  // Read data from file
  readFile(): string {
    if (!fs.existsSync(this.filePath)) {
      console.error('File does not exist.');
      return '';
    }
    return fs.readFileSync(this.filePath, 'utf8');
  }

  // Append new data to file
  updateFile(data: string): void {
    if (!fs.existsSync(this.filePath)) {
      console.error('File does not exist. Creating a new one.');
      this.writeFile(data);
    } else {
      fs.appendFileSync(this.filePath, '\n' + data, 'utf8');
      console.log(`File updated successfully: ${this.filePath}`);
    }
  }

  // Generate an HTML file
  generateHTML(): void {
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Generated HTML</title>
          <script src="script.js"></script>
      </head>
      <body>
          <h1>Hello from TypeScript!</h1>
          <p>This HTML file was generated by the TypeScript program.</p>
      </body>
      </html>
    `;

    this.writeFile(htmlContent);
  }
}

// Generate the HTML file
const htmlHandler = new FileHandler('index.html');
htmlHandler.generateHTML();
console.log('HTML file created successfully.');
