"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs");
var FileHandler = /** @class */ (function () {
    function FileHandler(filePath) {
        this.filePath = filePath;
    }
    // Write data to file (overwrites if file exists)
    FileHandler.prototype.writeFile = function (data) {
        fs.writeFileSync(this.filePath, data, 'utf8');
        console.log("File written successfully: ".concat(this.filePath));
    };
    // Read data from file
    FileHandler.prototype.readFile = function () {
        if (!fs.existsSync(this.filePath)) {
            console.error('File does not exist.');
            return '';
        }
        return fs.readFileSync(this.filePath, 'utf8');
    };
    // Append new data to file
    FileHandler.prototype.updateFile = function (data) {
        if (!fs.existsSync(this.filePath)) {
            console.error('File does not exist. Creating a new one.');
            this.writeFile(data);
        }
        else {
            fs.appendFileSync(this.filePath, '\n' + data, 'utf8');
            console.log("File updated successfully: ".concat(this.filePath));
        }
    };
    // Generate an HTML file
    FileHandler.prototype.generateHTML = function () {
        var htmlContent = "\n      <!DOCTYPE html>\n      <html lang=\"en\">\n      <head>\n          <meta charset=\"UTF-8\">\n          <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n          <title>Generated HTML</title>\n          <script src=\"script.js\"></script>\n      </head>\n      <body>\n          <h1>Hello from TypeScript!</h1>\n          <p>This HTML file was generated by the TypeScript program.</p>\n      </body>\n      </html>\n    ";
        this.writeFile(htmlContent);
    };
    return FileHandler;
}());
// Generate the HTML file
var htmlHandler = new FileHandler('index.html');
htmlHandler.generateHTML();
console.log('HTML file created successfully.');
